CREATE DATABASE Academia;
USE Academia;

CREATE TABLE Alunos (
id INT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(100) NOT NULL,
telefone VARCHAR(15) NOT NULL
);

CREATE TABLE Planos (
id INT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(50) NOT NULL,
preco_mensal DECIMAL(8,2) NOT NULL
);

CREATE TABLE Matriculas (
id INT AUTO_INCREMENT PRIMARY KEY,
id_aluno INT,
id_plano INT,
data_inicio DATE NOT NULL,
FOREIGN KEY (id_aluno) REFERENCES Alunos(id),
FOREIGN KEY (id_plano) REFERENCES Planos(id)
);

CREATE TABLE Aulas (
id INT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(50) NOT NULL,
horario TIME NOT NULL
);

CREATE TABLE Presencas (
id INT AUTO_INCREMENT PRIMARY KEY,
id_aluno INT,
id_aula INT,
data DATE NOT NULL,
FOREIGN KEY (id_aluno) REFERENCES Alunos(id),
FOREIGN KEY (id_aula) REFERENCES Aulas(id)
);